export const DAYS = [
  {
    day: "FRIDAY",
    date: "March 20",
    resort: "Keystone",
    color: "#1a5276",
    accent: "#2980b9",
    passNote: "USE EPIC PASS #1",
    passExplain:
      "Covers River Run Gondola sightseeing access + 20% off on-mountain dining via Epic Mountain Rewards",
    items: [
      {
        time: "9:45 AM",
        title: "Drive from Airbnb to Keystone",
        desc: "Breckenridge \u2192 Keystone is only ~20 min. Arrive early to get settled before your meeting.",
        tag: "DRIVE",
        icon: "\uD83D\uDE97",
        mapQuery: "Keystone Resort, Keystone, CO",
        travelTime: null,
        travelMode: null,
      },
      {
        time: "10:15 \u2013 11:30 AM",
        title: "Meeting @ Inxpot Coffeehouse",
        desc: "Inxpot is in River Run Village right near the gondola \u2014 library-lounge vibe, free WiFi, great coffee and breakfast burritos. Opens at 7am. Post up with a coffee, take your 10:30\u201311:30 meeting, and you\u2019re already in the village when you\u2019re done.",
        tag: "MEETING",
        icon: "\uD83D\uDCBC",
        mapQuery: "Inxpot Coffeehouse, Keystone, CO",
        travelTime: "5 min",
        travelMode: "walk",
      },
      {
        time: "11:30 AM \u2013 1:00 PM",
        title: "Lunch & Fireside Hang",
        desc: "You\u2019re already in the village \u2014 grab lunch at New Moon Caf\u00e9 (classic rock vibes, full menu all day) or Kickapoo Tavern. Warm up by the big firepit in River Run Village Plaza.",
        tag: "FOOD",
        icon: "\uD83C\uDF7D\uFE0F",
        mapQuery: "River Run Village, Keystone, CO",
        travelTime: "2 min",
        travelMode: "walk",
      },
      {
        time: "1:00 \u2013 3:00 PM",
        title: "Gondola Up & Mountain Views",
        desc: "Ride the River Run Gondola to the top of Dercum Mountain with your Epic Pass. Explore the Snow Fort, check out the views from the summit, grab a hot chocolate or drink at the mountaintop lodge. Take your time \u2014 ride back down whenever you\u2019re ready. Browse the shops in River Run Village after.",
        tag: "ACTIVITY",
        icon: "\uD83C\uDFD4\uFE0F",
        mapQuery: "River Run Gondola, Keystone, CO",
        travelTime: "2 min",
        travelMode: "walk",
      },
      {
        time: "~2:00 PM",
        title: "\uD83E\uDD1D Meetup #1 \u2014 Summit House, Top of Dercum",
        desc: "Text your friends to meet you at Summit House at the top of the gondola around 2 PM for a drink. Blue/black skiers can get there easily from anywhere on the mountain. You\u2019re already up there \u2014 grab a table and wait for them. Quick hangout before they hit more runs and you ride down.",
        tag: "MEETUP",
        icon: "\uD83E\uDD1D",
        mapQuery: "Summit House, Keystone Resort, CO",
        travelTime: null,
        travelMode: null,
      },
      {
        time: "3:00 \u2013 5:00 PM",
        title: "Brewery Hop",
        desc: "Summit County has ~8 craft breweries. Hit a couple to ease into the weekend. Remember: altitude makes drinks hit harder.",
        tag: "DRINKS",
        icon: "\uD83C\uDF7A",
        mapQuery: "Breweries near Keystone, CO",
        travelTime: "10 min",
        travelMode: "drive",
      },
      {
        time: "~4:30 PM",
        title: "\uD83E\uDD1D Meetup #2 \u2014 Kickapoo Tavern, River Run",
        desc: "Lifts close around 4 PM. Tell your crew to ski their last run down to River Run and meet you at Kickapoo Tavern \u2014 it\u2019s right across the bridge from the gondola, has a sun deck with views of skiers coming down. This is THE apr\u00e8s spot at Keystone. Regroup here and head to dinner together.",
        tag: "MEETUP",
        icon: "\uD83E\uDD1D",
        mapQuery: "Kickapoo Tavern, Keystone, CO",
        travelTime: null,
        travelMode: null,
      },
      {
        time: "5:30 \u2013 7:00 PM",
        title: "Dinner",
        desc: "Grab dinner before the show. Kickapoo Tavern in River Run is a solid option, or Zuma Roadhouse for casual Mexican. Use your Epic Pass for 20% off on-mountain dining options.",
        tag: "FOOD",
        icon: "\uD83C\uDF7D\uFE0F",
        mapQuery: "Kickapoo Tavern, Keystone, CO",
        travelTime: "5 min",
        travelMode: "walk",
      },
      {
        time: "7:30 \u2013 10:00 PM",
        title: "Winter Comedy Series @ Warren Station",
        desc: "Comedy Works Denver brings the laughs to Keystone. Great warm-up night before the big Saturday. Tickets required. Quick 20-min drive back to your Airbnb after.",
        tag: "EVENT",
        icon: "\uD83C\uDF64",
        mapQuery: "Warren Station Center, Keystone, CO",
        travelTime: "5 min",
        travelMode: "walk",
      },
    ],
  },
  {
    day: "SATURDAY",
    date: "March 21",
    resort: "Vail",
    color: "#7b241c",
    accent: "#e74c3c",
    passNote: "USE EPIC PASS #2",
    passExplain:
      "Covers Gondola One foot-passenger access (saves ~$65\u201375 sightseeing ticket) + 20% off on-mountain dining",
    items: [
      {
        time: "9:00 AM",
        title: "Drive to Vail",
        desc: "Breckenridge \u2192 Vail is ~45 min via I-70 West. Get there early to soak it in.",
        tag: "DRIVE",
        icon: "\uD83D\uDE97",
        mapQuery: "Vail Village, Vail, CO",
        travelTime: null,
        travelMode: null,
      },
      {
        time: "10:00 \u2013 11:30 AM",
        title: "Gondola One \u2192 Lunch at The 10th",
        desc: "Use your Epic Pass to ride Gondola One up to Mid-Vail. Have a long, leisurely lunch at The 10th \u2014 upscale mountain cuisine, craft cocktails, Gore Range views. Open to non-skiers. The DJ on the back patio has been playing select weekends this season too.",
        tag: "FOOD",
        icon: "\uD83C\uDF7D\uFE0F",
        mapQuery: "The 10th Restaurant, Vail, CO",
        travelTime: "15 min",
        travelMode: "walk",
      },
      {
        time: "~11:00 AM",
        title: "\uD83E\uDD1D Meetup #1 \u2014 The 10th, Mid-Vail",
        desc: "Have your friends ski to Mid-Vail (top of Gondola One) and join you for lunch at The 10th around 11. It\u2019s a natural midpoint on the mountain \u2014 blue/black skiers pass through here constantly. Share a meal with mountain views, then they head back out and you ride down to the village.",
        tag: "MEETUP",
        icon: "\uD83E\uDD1D",
        mapQuery: "The 10th Restaurant, Vail, CO",
        travelTime: null,
        travelMode: null,
      },
      {
        time: "12:00 \u2013 12:45 PM",
        title: "Explore Vail Village",
        desc: "Walk the pedestrian village. Window shop, coffee, or grab a drink at Pepi\u2019s Bar (classic Austrian apr\u00e8s vibe since the 1960s). Then head over to Avanti at Golden Peak to get a good spot before it fills up.",
        tag: "EXPLORE",
        icon: "\uD83C\uDFD8\uFE0F",
        mapQuery: "Vail Village, Vail, CO",
        travelTime: "10 min",
        travelMode: "walk",
      },
      {
        time: "1:00 \u2013 5:00 PM",
        title: "Experts Only Popup \u2014 Devault @ Avanti F&B",
        desc: "Your anchor for the afternoon. Avanti is at the base of Golden Peak \u2014 food hall with 5 stalls (burgers, ramen, pizza, Mediterranean, caviar bar), two full bars, and the biggest patio in Vail with mountain views and fire pits. Grab food, post up with drinks, and catch Devault\u2019s set. Camp here and enjoy it. Note: Flamingosis plays Express Lift Bar (2\u20135 PM) and RAW CUTS ft. salute plays Solaris Plaza (3\u20136 PM) \u2014 both free and walkable if you want to pop over, but Avanti is the move.",
        tag: "\u26A1 KEY EVENT",
        icon: "\uD83D\uDD25",
        mapQuery: "Avanti Food & Beverage, Vail, CO",
        travelTime: "10 min",
        travelMode: "walk",
      },
      {
        time: "~3:30 PM",
        title: "\uD83E\uDD1D Meetup #2 \u2014 Avanti F&B, Golden Peak Base",
        desc: "Tell your friends to take their last few runs down to Golden Peak (Riva Bahn Express chair drops right at Avanti\u2019s door). They ski in, boots off, grab food and drinks, and join the Devault set with you. Perfect convergence point \u2014 they get last runs, you\u2019ve been vibing all afternoon. Together for the rest of the night.",
        tag: "MEETUP",
        icon: "\uD83E\uDD1D",
        mapQuery: "Avanti Food & Beverage, Vail, CO",
        travelTime: null,
        travelMode: null,
      },
      {
        time: "5:00 \u2013 6:00 PM",
        title: "Solaris Plaza or Ford Park",
        desc: "Option A: Walk to Solaris Plaza and catch the tail end of the RAW CUTS set (free, runs until 6 PM). Option B: If you scored resale tix for Experts Only @ Ford Park (SIDEPIECE, Aspens \u2014 SOLD OUT on primary, check AXS Resale/StubHub, 21+), head there at 5 PM. Option C: Stay at Avanti and keep the vibe going.",
        tag: "DRINKS",
        icon: "\uD83C\uDFA7",
        mapQuery: "Solaris Plaza, Vail, CO",
        travelTime: "5 min",
        travelMode: "walk",
      },
      {
        time: "6:30 \u2013 8:30 PM",
        title: "Dinner in Vail Village",
        desc: "Refuel before the late night. Alpine Pizza for Detroit-style slices (local favorite), Avanti if you\u2019re still there, or go bigger at Mountain Standard or Sweet Basil. Use your Epic Pass for 20% off on-mountain dining.",
        tag: "FOOD",
        icon: "\uD83C\uDF7D\uFE0F",
        mapQuery: "Vail Village, Vail, CO",
        travelTime: "10 min",
        travelMode: "walk",
      },
      {
        time: "9:00 PM \u2013 Late",
        title: "Late Night in Vail Village",
        desc: "Chasing Rabbits \u2014 underground cocktail bar with DJs, arcade games, and likely an EO afterparty. Shakedown Bar \u2014 live music, cheap drinks, always packed. Bridge Street Bar \u2014 the dance floor spot. Plan a designated driver or rideshare back to Breck (~45 min).",
        tag: "NIGHTLIFE",
        icon: "\uD83C\uDF19",
        mapQuery: "Chasing Rabbits, Vail, CO",
        travelTime: "5 min",
        travelMode: "walk",
      },
    ],
  },
  {
    day: "SUNDAY",
    date: "March 22",
    resort: "Breckenridge",
    color: "#1e6e3e",
    accent: "#27ae60",
    passNote: "NO PASS NEEDED",
    passExplain:
      "BreckConnect Gondola is FREE for everyone \u2014 no ticket or pass required. Save your passes for Fri & Sat.",
    items: [
      {
        time: "10:00 AM",
        title: "Sleep In & Stroll Into Town",
        desc: "You\u2019re already near Breck at your Airbnb \u2014 no long drive needed. You earned the late start after Saturday in Vail.",
        tag: "CHILL",
        icon: "\uD83D\uDE34",
        mapQuery: "Breckenridge, CO",
        travelTime: null,
        travelMode: null,
      },
      {
        time: "11:00 AM \u2013 12:30 PM",
        title: "BreckConnect Gondola + Coffee",
        desc: "Ride the FREE gondola from town up to the base of Peak 8. Stunning views, fresh mountain air, zero cost. Grab coffee and breakfast at a caf\u00e9 on Main Street before or after.",
        tag: "FREE",
        icon: "\uD83D\uDEA1",
        mapQuery: "BreckConnect Gondola, Breckenridge, CO",
        travelTime: "10 min",
        travelMode: "drive",
      },
      {
        time: "12:30 \u2013 2:30 PM",
        title: "Main Street Stroll & Lunch",
        desc: "Breckenridge\u2019s historic Main Street is the most walkable mountain town in Colorado. Browse shops, galleries, and the Breckenridge Arts District. Grab lunch \u2014 tons of options from casual to upscale.",
        tag: "EXPLORE",
        icon: "\uD83D\uDECD\uFE0F",
        mapQuery: "Main Street, Breckenridge, CO",
        travelTime: "5 min",
        travelMode: "walk",
      },
      {
        time: "~12:30 PM",
        title: "\uD83E\uDD1D Meetup #1 \u2014 Base of Peak 8, T-Bar or Ten Mile Station",
        desc: "Have your friends ski to the base of Peak 8 around 12:30 for a lunch break. You can walk from the top of the BreckConnect Gondola right to the base area. Ten Mile Station (mid-mountain, accessible by gondola) or the lodge at the base of Peak 8 both work. Quick meal together, then they head back up for afternoon laps.",
        tag: "MEETUP",
        icon: "\uD83E\uDD1D",
        mapQuery: "Peak 8 Base, Breckenridge, CO",
        travelTime: null,
        travelMode: null,
      },
      {
        time: "2:30 \u2013 4:00 PM",
        title: "Recovery Activity \u2014 Pick Your Vibe",
        desc: "Option A: Spa day at Blue Sage (book ahead). Option B: Slope-side drinks at the base of Peak 8 or 9 \u2014 watch your friends ski, soak up the sun. Option C: Gallery hop in the Arts District or hit a brewery.",
        tag: "CHILL",
        icon: "\uD83E\uDDD6",
        mapQuery: "Blue Sage Spa, Breckenridge, CO",
        travelTime: "5 min",
        travelMode: "walk",
      },
      {
        time: "4:00 \u2013 6:00 PM",
        title: "Apr\u00e8s on Main Street & Closing Drinks",
        desc: "Wrap the weekend on a high note. Breck\u2019s Main Street apr\u00e8s scene is lively \u2014 Broken Compass Brewing, The Canteen, or Cecilia\u2019s for cocktails. Toast to a legendary weekend.",
        tag: "DRINKS",
        icon: "\uD83E\uDD42",
        mapQuery: "Broken Compass Brewing, Breckenridge, CO",
        travelTime: "10 min",
        travelMode: "walk",
      },
      {
        time: "~4:00 PM",
        title: "\uD83E\uDD1D Meetup #2 \u2014 Main Street Apr\u00e8s",
        desc: "Lifts close around 4 PM. Skiers take their last run down to the base of Peak 9 \u2014 it drops right onto Main Street. Pick a bar (Broken Compass is a great call), grab a table, and text the crew your location. Everyone together for the closing drinks of the weekend.",
        tag: "MEETUP",
        icon: "\uD83E\uDD1D",
        mapQuery: "Broken Compass Brewing, Breckenridge, CO",
        travelTime: null,
        travelMode: null,
      },
      {
        time: "6:00 PM+",
        title: "Back to the Airbnb",
        desc: "Short trip back to your Airbnb. Hot tub, takeout, relive the weekend. Legendary three days in the books.",
        tag: "CHILL",
        icon: "\uD83C\uDFE0",
        mapQuery: null,
        travelTime: "10 min",
        travelMode: "drive",
      },
    ],
  },
];

export const tagColors = {
  HOME: { bg: "#f5f5f5", text: "#555" },
  MEETING: { bg: "#e8eaf6", text: "#283593" },
  MEETUP: { bg: "#fff8e1", text: "#f57f17" },
  DRIVE: { bg: "#ecf0f1", text: "#7f8c8d" },
  ACTIVITY: { bg: "#ebf5fb", text: "#2980b9" },
  EXPLORE: { bg: "#fef9e7", text: "#b7950b" },
  FOOD: { bg: "#fdedec", text: "#c0392b" },
  DRINKS: { bg: "#fef5e7", text: "#e67e22" },
  EVENT: { bg: "#f4ecf7", text: "#8e44ad" },
  "FREE MUSIC": { bg: "#eafaf1", text: "#1a8a4a" },
  "\u26A1 KEY EVENT": { bg: "#fff3e0", text: "#d35400" },
  TICKETED: { bg: "#fce4ec", text: "#c62828" },
  NIGHTLIFE: { bg: "#ede7f6", text: "#5e35b1" },
  CHILL: { bg: "#e8f5e9", text: "#388e3c" },
  FREE: { bg: "#e0f7fa", text: "#00838f" },
};
